// Async Actions
export const FETCH_PROFILE_DETAILS = "FETCH_PROFILE_DETAILS";
export const FETCH_PROFILE_DETAILS_LOADING = "FETCH_PROFILE_DETAILS_LOADING";
export const FETCH_PROFILE_DETAILS_SUCCESS = "FETCH_PROFILE_DETAILS_SUCCESS";
export const FETCH_PROFILE_DETAILS_ERROR = "FETCH_PROFILE_DETAILS_ERROR";

export const FETCH_REPOSITORIES = "FETCH_REPOSITORIES";
export const FETCH_REPOSITORIES_LOADING = "FETCH_REPOSITORIES_LOADING";
export const FETCH_REPOSITORIES_SUCCESS = "FETCH_REPOSITORIES_SUCCESS";
export const FETCH_REPOSITORIES_ERROR = "FETCH_REPOSITORIES_ERROR";
